// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{f675a9f9-db5f-4791-88df-8cf03895c9c0}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1750738950);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 142);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c8439399-5de4-4902-b645-1995fa2c8688}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240311145044");
user_pref("browser.startup.homepage_override.mstone", "124.0");
user_pref("browser.startup.lastColdStartupCheck", 1750738953);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.iniFile.exists.appversion", "124.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.raspberrypios.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.uBlock0@raymondhill.net", true);
user_pref("extensions.installedDistroAddon.uanaughtylist@raspberrypi.com", true);
user_pref("extensions.lastAppBuildId", "20240311145044");
user_pref("extensions.lastAppVersion", "124.0");
user_pref("extensions.lastPlatformVersion", "124.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"uanaughtylist@raspberrypi.com\":\"39a1d7d0-8788-4513-a0de-eb156abe0812\",\"uBlock0@raymondhill.net\":\"211db486-7551-4813-97e9-7abc98ce4c09\",\"formautofill@mozilla.org\":\"d5f04c35-811e-4bd2-a8b2-136feea3ed61\",\"pictureinpicture@mozilla.org\":\"3916b02f-85b2-4c03-8778-986220ae1b74\",\"screenshots@mozilla.org\":\"65293a51-b029-4784-9934-dd342c2053e4\",\"webcompat-reporter@mozilla.org\":\"67b6661f-fc50-4556-b1ec-8b81285af24c\",\"webcompat@mozilla.org\":\"1f387a23-d79c-4ba4-82ab-c12f7d1cc785\",\"default-theme@mozilla.org\":\"b976387b-a2b0-4780-bbca-e552accaff40\",\"addons-search-detection@mozilla.com\":\"9ecaef23-9d44-4ff8-a116-d3e8953284a4\",\"google@search.mozilla.org\":\"810dc9b4-c2db-499a-b104-373f269727c7\",\"wikipedia@search.mozilla.org\":\"f41783dd-6596-42b1-a039-cf7c66c410a7\",\"bing@search.mozilla.org\":\"dd13ad97-ed95-4873-a98f-e75f2df13dfb\",\"ddg@search.mozilla.org\":\"8e32d9cd-4094-44d3-bf6a-8859d1a04404\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "f1048d0c-995a-46e9-8241-865b5a5f2661");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.telemetry.cachedClientID", "fd5ec1d0-4f3f-477d-a496-43cd3e653aa5");
user_pref("toolkit.telemetry.previousBuildID", "20240311145044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
